#!/bin/bash

#cd ~
#git clone https://aur.archlinux.org/yay.git
#cd ~/yay
#makepkg -si
#cd ~
#rm -rf ~/yay

yay --aururl "https://aur.tuna.tsinghua.edu.cn" --save
yay -S --noconfirm xdg-user-dirs
xdg-user-dirs-update
yay -S --noconfirm papirus-icon-theme latte-dock kvantum-qt5 yakuake spectacle gwenview zsh
yay -S --noconfirm fcitx-im kcm-fcitx fcitx-rime
echo 'GTK_IM_MODULE=fcitx' >> ~/.pam_environment
echo 'QT_IM_MODULE=fcitx' >> ~/.pam_environment
echo 'XMODIFIERS=@im=fcitx' >> ~/.pam_environment
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
sed -i "1,12s/=\"robbyrussell\"/=\"ys\"/g" ~/.zshrc
sed -i "71s/(git)/(git sudo zsh-autosuggestions zsh-syntax-highlighting)/g" ~/.zshrc
chsh -s /bin/zsh
yay -S --noconfirm google-chrome
yay --answerclean a --answerdiff n -S --noconfirm tela-icon-theme-git
yay --answerclean a --answerdiff n -S --noconfirm mcmojave-kde-theme-git
